#page setting
title: 망상코더의 망상노트
description: "mangsang blog, build with Jekyll."
theme: jekyll-theme-hacker
author:
  name: "망상코더"
  email: "koock1994@gmail.com"
  url: "https://kooock.github.io/"


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
enable_coderay: false